export_readings:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: smgw_han
    from_datetime:
      required: true
      selector:
        datetime:
    to_datetime:
      required: true
      selector:
        datetime:
    download_cms:
      required: true
      default: false
      selector:
        boolean:
    write_csv:
      required: true
      default: false
      selector:
        boolean:
    write_xlsx:
      required: true
      default: false
      selector:
        boolean:
