export_readings:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: smgw_han
    from_datetime:
      required: true
      selector:
        datetime:
    to_datetime:
      required: true
      selector:
        datetime:
    download_cms:
      required: true
      default: false
      selector:
        boolean:
    write_csv:
      required: true
      default: false
      selector:
        boolean:
    write_xlsx:
      required: true
      default: false
      selector:
        boolean:

export_period:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: smgw_han
    period:
      required: true
      default: last_month
      selector:
        select:
          mode: dropdown
          translation_key: export_period
          options:
            - yesterday
            - last_7_days
            - last_30_days
            - current_month
            - last_month
    download_cms:
      required: true
      default: false
      selector:
        boolean:
    write_csv:
      required: true
      default: false
      selector:
        boolean:
    write_xlsx:
      required: true
      default: false
      selector:
        boolean:
